refactor: Added noImplicitAny Support
Seneca-CDOT/plumadriver pull request #202
Opened 2020-09-25 16:46 UTC by MeisterRed

Solved most of the `noImplicitAny` subtask in #32 

I've given many parameters specific types and typed a few variables as any (no idea what type to give them) in order to support the `noImplicitAny` rule. This pull request doesn't solve all errors since there's still a few things that need to be fixed (a few libraries need to be installed and @pynnl will be handling the rest of `Session.ts`) so I will save those for a separate pull request. The noImplicitAny rule will be false for the time being.

My changes aren't exactly perfect so I am hoping for some feedback before this gets added to master. I'll be happy to make any requested changes as soon as possible.

2020-09-25 19:01 UTC, pynnl requested changes

2020-09-25 19:01 UTC, pynnl commented on src/utils/utils.ts
> +    (req.sessionRequest as Pluma.Request).command = plumaCommand;
You can use optional chaining instead of casting, for types which can be `undefined` or `null`. There are other code like this, fix them the same way.

2020-09-28 13:46 UTC, MeisterRed commented on src/Browser/BrowserConfig.ts
> +    return (window: any): void => {
I originally had the type as `DOMWindow` but it seems to be having issues with `BeforeParse` in the `types.d.ts` file (Which is also of type `DOMWindow`)

2020-09-28 13:50 UTC, MeisterRed commented on src/Types/types.d.ts
> +      | unhandledPromptBehavior;
A few errors popped up saying "No index signature with a parameter of `string` was found on type `BrowserOptions`" so I created the index signature shown here to fix that.

2020-09-28 14:00 UTC, pynnl commented on src/Types/types.d.ts
> +      | unhandledPromptBehavior;
`BrowserOptions` isn't supposed to have any properties except the three already defined. The right way to fix that error is to validate the property name to make sure it is one of those three.

2020-09-28 14:18 UTC, MeisterRed commented on src/Browser/Browser.ts
>      });
What do you mean by "spead `capabilities` into `browerOptions`"?

2020-09-28 14:22 UTC, pynnl commented on src/Browser/Browser.ts
>      });
I meant using spread operator. But nevermind, they are not the same logic, my bad.

2020-09-28 14:35 UTC, MeisterRed commented on src/Browser/Browser.ts
> +    error: { statusCode: number },
the type of `error` isn't `WebdriverError`. The `error` property just accepts an object that has the property of `statusCode`. I couldn't determine what the actual type should be for `error` so I went with this option

2020-09-28 15:07 UTC, pynnl commented on src/Browser/Browser.ts
> +    error: { statusCode: number },
You're right, the error seems to come from `JSDOM`, and type of a response.

2020-09-28 20:10 UTC, MeisterRed commented on src/WebElement/WebElement.ts
> +    return this.element.getAttribute(name) || ' ';
It has originally fixed an error in the past but it seems like it's no longer needed since it doesn't yield an error anymore

2020-09-29 14:52 UTC, MeisterRed commented on src/WebElement/WebElement.ts
> +    //const temp = implSymbol as keyof HTMLElement;
Right. I originally deleted this comment but I guess it accidentally came back while I was squashing commits. It has been removed

2020-09-29 14:53 UTC, MeisterRed commented on src/routes/cookies.ts
> +//import { Request, Response, NextFunction } from 'express';
Sorry about the leftover unused comments. I've removed them from this file and the others in the routes folder

2020-10-01 15:15 UTC, pynnl submitted a review, later dismissed

2020-10-01 15:18 UTC, pynnl reviewed
LGTM. You might wanna clean up commit history though. There're some with same commit messages, and there're also a lot of merging.

2020-10-01 15:21 UTC, MeisterRed commented
> LGTM. You might wanna clean up commit history though. There're some with same commit messages, and there're also a lot of merging.
Right, sorry about that. Would it be possible for me to squash the commits and have the previous commits disappear from this pull request without any issue? Should I close this one and create a new one after squashing?

2020-10-01 15:22 UTC, zthaver approved these changes
Looks Good! Maybe you want to squash the commits as @pynnl  suggested.

2020-10-01 16:02 UTC, poftadeh commented on src/CapabilityValidator/CapabilityValidator.ts
> +          this.valid = capability.constructor === Object;
This is now redundant given we are determining object type in the previous line. It's also not a safe way to check if something is an object, so probably should be refactored.

2020-10-01 16:03 UTC, pynnl submitted a review, later dismissed

2020-10-01 16:05 UTC, zthaver submitted a review, later dismissed

2020-10-01 16:06 UTC, poftadeh commented on src/Browser/Browser.ts
> +    //typeguard function for object
This comment can be omitted.

2020-10-01 16:21 UTC, MeisterRed commented on tsconfig.json
> +    "target": "ES2019",
It was suggested that I use optional chaining instead of type casting in the `utils,,ts` file. I was running into syntax errors in the tests while implementing this change and after asking for help, I was told that node didn't support optional chaining below v13. We changed the target to be lower in order to support optional chaining in that file

2020-10-01 16:23 UTC, MeisterRed commented on tsconfig.json
> +    "noImplicitAny": false
It's currently set to false because `session.ts` is being worked on by another member and some files need certain libraries installed. We've decided to split those into a separate pull request for the time being but if you suggest I install those libraries in this one, I can do that

2020-10-01 16:28 UTC, pynnl commented on tsconfig.json
> +    "noImplicitAny": false
You can put a `@ts-nocheck` at the top of the file you want to skip, say `Session.ts`. Then you can enable `noImplicitAny`.

2020-10-01 16:30 UTC, MeisterRed commented on tsconfig.json
> +    "noImplicitAny": false
Alright, Thanks. I'll work on fixing everything up now

2020-10-01 17:04 UTC, poftadeh commented on tsconfig.json
> +    "target": "ES2019",
Okay, that makes sense. Downcasting is needed given the current LTS version. I think making an `.nvmrc` file at some point to help contributors sync to the right version would be helpful in the repo. It's a PR I can make at some point.

2020-10-01 18:24 UTC, MeisterRed commented on src/CapabilityValidator/CapabilityValidator.ts
> +          this.valid = capability.constructor === Object;
I added an if statement there because the variable type change from `any` to `unknown`.  `capability` is still shown to be `unknown` before it reaches the `this.valid` line, so I thought that adding an if statement that checks if it was an object would be a great way to define the variable type within that case. I would like a suggestion on what you think would be the best way to refactor all of this because the last thing I would want to do is make changes that don't turn out to be great in the end.

2020-10-01 18:27 UTC, MeisterRed commented on src/Browser/Browser.ts
> +      return object !== undefined;
I changed the return statement in the function so that it specifically checks if the object being passed in is actually an object type. Hopefully this is enough to make sure that other variable types don't actually pass through this check

2020-10-01 18:39 UTC, pynnl commented on src/CapabilityValidator/CapabilityValidator.ts
> +          this.valid = capability.constructor === Object;
@MeisterRed What he meant is line `56` and `57` does the exact same thing, so you can instead do `this.valid = isObject(capability)`. The type guard logic is not safe, for example `1 !== undefined` but `1` is not an `object`. The proper way could be something like `typeof arg === 'object' && arg !== null`. Also the type guard function should be in `utils` so it can be reused somewhere else.

P/S: just a side node, when checking for `undefined`, you should use `typeof` instead of comparing directly to the `undefined object`, because it can be changed.

2020-10-01 18:41 UTC, MeisterRed commented on src/CapabilityValidator/CapabilityValidator.ts
> +          this.valid = capability.constructor === Object;
Alright, thank you so much

2020-10-02 20:35 UTC, pynnl approved these changes

2020-10-02 20:35 UTC, pynnl commented on src/Browser/BrowserConfig.ts
> +    for (const option in options) {
This is fine for now since we know `options` is plain object obtained from the request body. Just an additional info, `for...in` will loop through inherited properties as well, so if you just want to loop through own properties as [W3C mentioning](https://www.w3.org/TR/webdriver/#dfn-own-properties), you should use `Object.keys`

2020-10-02 21:56 UTC, zthaver approved these changes

2020-10-05 15:38 UTC, poftadeh approved these changes
LGTM.

2020-10-05 15:47 UTC, merged