feat: Get Element Property Endpoint
Seneca-CDOT/plumadriver pull request #207
Opened 2020-10-08 18:31 UTC by zthaver

- Added Get Element Property Endpoint

- Added tests for Get Element Property Endpoint

Closes #190

2020-10-08 21:19 UTC, poftadeh requested changes

2020-10-08 21:19 UTC, poftadeh commented on src/WebElement/WebElement.ts
> +    if (!property) {
According to spec, `null` should be returned if the result of retrieving the property is `undefined`, not if the argument passed by the client is `undefined`. This is likely because you'll run into problems passing undefined as a JSON response back to the client, i.e. `JSON.stringify({value: undefined}) // "{}"`

Check for undefined in line 77 instead.

2020-10-08 21:19 UTC, poftadeh commented on test/jest/get-element-property.test.js
> +    expect(await elementProperty('#divtest', 'title')).toBe('baz');
Please test for a `null` condition as well, since this is a possibility outlined in the spec.

2020-10-09 03:52 UTC, poftadeh reviewed
Nearly there, just a couple small changes:

2020-10-09 04:14 UTC, zthaver commented on src/WebElement/WebElement.ts
> +  getProperty(property?: string): unknown {
Since the propertyName passed to this function is optional, the compiler won't allow us to drop the ? without causing an error. Should I leave it in or give a default value?

2020-10-09 04:31 UTC, poftadeh commented on src/WebElement/WebElement.ts
> +  getProperty(property?: string): unknown {
Can we do an `isString` validation on `property` prior to passing it to this function?

2020-10-09 04:51 UTC, zthaver commented on src/WebElement/WebElement.ts
> +  getProperty(property?: string): unknown {
``         .getProperty(
      typeof urlVariables.propertyName === 'string'
        ? urlVariables.propertyName
        : undefined,
    );
``
I tried this, but it still complains that type  string|undefined cannot be assigned to undefined. Should I make it  something else? Also, isn't it not possible for property name to be undefined?

2020-10-09 05:23 UTC, poftadeh commented on src/WebElement/WebElement.ts
> +  getProperty(property?: string): unknown {
The thing is, the `propertyName` should never be undefined (we can't hit this endpoint without providing one). The problem seems to be fundamentally with `req.sessionRequest` be typed as possibly undefined:

`routes/elements.ts`
```js
  if (req.sessionRequest) {
    req.sessionRequest.urlVariables.propertyName = req.params.propertyName;
  }
```
But any endpoint starting with `/session/:sessionId` should always have a `sessionRequest`:

`routes/index.ts`
```js
router.use('/session/:sessionId', (req, res, next) => {
  const sessionsManager = req.app.get('sessionManager');
  const request: Pluma.Request = {
    urlVariables: req.params,
    parameters: req.body,
    command: '',
  };
  req.sessionId = req.params.sessionId;
  req.session = sessionsManager.findSession(req.sessionId);
  req.sessionRequest = request;
  next();
});
```

I think we can remove the `?` and possibly every `if (req.sessionRequest)` check found in routes starting with `/session/:sessionId`:

`Types/types.d.ts`
```js
    interface Request {
      sessionId?: string;
      session?: Session;
      sessionRequest: Pluma.Request;  // removed '?'
    }
```
@pynnl is this doable based on your work on #32?

2020-10-09 14:24 UTC, pynnl commented on src/WebElement/WebElement.ts
> +  getProperty(property?: string): unknown {
There are routes which don't have session related fields such as `/status`. If we remove the optional on `sessionRequest` and **accidentally** access it on those routes, the code will break on runtime.

The way `Express` is typed makes it hard to have different types on different routes. There's one other option, which is to explicitly define `req`, `res`,... in every routes. It'll be a bit complicated to augment the existing types as far as I know, but I believe it's the most viable solution right now. We can have another PR for that. What do you think @poftadeh @zthaver @MeisterRed ?

2020-10-09 16:08 UTC, zthaver commented on src/WebElement/WebElement.ts
> +  getProperty(property?: string): unknown {
So, we have decided to keep the session request and the property name as is and make these changes in another PR.

2020-10-09 16:34 UTC, poftadeh commented on src/WebElement/WebElement.ts
> +  getProperty(property?: string): unknown {
Moving it to a new issue is best, I agree. We can move discussion about this there as well. This PR can be merged as-is in that case.

2020-10-09 16:35 UTC, poftadeh approved these changes

2020-10-09 16:57 UTC, manekenpix approved these changes

2020-10-09 16:58 UTC, pynnl approved these changes

2020-10-09 16:58 UTC, merged