feat: added get computed role endpoint
Seneca-CDOT/plumadriver pull request #216
Opened 2020-10-20 15:52 UTC by zthaver

- Added get computed role endpoint
- Added tests for endpoint 
Closes  #214

2020-10-20 19:29 UTC, manekenpix commented on README.md
> +- [x] [**Get Computed Role:**](https://www.w3.org/TR/webdriver/#dfn-get-computed-label) GET /session/{session id}/element/{element id}/computedlabel
Should this line say `computedrol` instead of `computedlabel`?

2020-10-20 23:35 UTC, pynnl requested changes

2020-10-20 23:35 UTC, pynnl commented on src/WebElement/WebElement.ts
> +    return this.getElementAttribute('role');
I think this is not qualified as w3c spec [here](https://w3c.github.io/aria/#introroles). Role can be a list of tokens, and need to be split and matched to a valid role.

2020-10-21 01:26 UTC, manekenpix commented on test/jest/e2e/get-computed-role.test.js
> +});
Add newline here.

2020-10-22 04:42 UTC, pynnl commented on src/WebElement/WebElement.ts
> +  /**
Please add a blank line here.

2020-10-22 05:06 UTC, pynnl requested changes

2020-10-22 14:44 UTC, zthaver commented on src/WebElement/WebElement.ts
> +    splitRole?.forEach(function(roles) {
The w3c specification specifies: Separate the attribute value string for that attribute into a sequence of whitespace-free substrings by separating on whitespace.That is why I did this.

2020-10-22 14:45 UTC, zthaver commented on src/constants/constants.ts
> +export const roleList = [
https://www.w3.org/WAI/PF/aria/roles here is the link, i'll also put it in the code so you can refer to it

2020-10-22 15:04 UTC, pynnl commented on src/WebElement/WebElement.ts
> +    splitRole?.forEach(function(roles) {
I mean the whole logic. Sorry for not being clear. The string `alert select` will give `undefined` with the current code.

2020-10-22 15:09 UTC, zthaver commented on src/WebElement/WebElement.ts
> +    splitRole?.forEach(function(roles) {
Oh, I see you're right, I modified the test to see your point

2020-10-22 15:17 UTC, pynnl commented on src/WebElement/WebElement.ts
> +    splitRole?.forEach(function(roles) {
Yup. There are three cases the test should cover:
- The valid role is the first token
- The valid role is the last token
- There are two valid roles, thus the first one should be picked

2020-10-23 18:33 UTC, pynnl reviewed
Looking good, just needs a few small changes.

2020-10-23 18:33 UTC, pynnl commented on test/jest/e2e/get-computed-role.test.js
> +          <li role="log alerts">Open file…</li>
Should it be `alert`?

2020-10-23 18:33 UTC, pynnl commented on src/WebElement/WebElement.ts
> +  getRole(): unknown {
Why does it return `unknown`? Isn't it there are only two cases, string or null?

2020-10-23 18:33 UTC, pynnl commented on src/WebElement/WebElement.ts
> +        rolesList => splitRole[i] === rolesList,
nit: you are looping a list of roles, so the item should be called `role`, not `rolesList`

2020-10-23 18:33 UTC, pynnl commented on src/WebElement/WebElement.ts
> +      if (foundRole != null) {
`Array.find()` returns the item or `undefined`, and it's the one should be compared to. The reason it's working with `null` is that you're using loose comparison (eslint should have forced strict comparison though, not sure why it doesn't)

2020-10-23 18:59 UTC, zthaver commented on test/jest/e2e/get-computed-role.test.js
> +          <li role="log alerts">Open file…</li>
In this case, it doesn't matter as log is a valid role, I guess

2020-10-23 19:01 UTC, pynnl commented on test/jest/e2e/get-computed-role.test.js
> +          <li role="log alerts">Open file…</li>
But isn't this the case where we have two valid roles? Because with the logic in the previous commit, it would return the last match instead of the first one. We need to make sure it won't happen.

2020-10-23 19:26 UTC, pynnl submitted a review, later dismissed
LGTM now, thanks for quick response. Just a suggestion, your logic can be shortened into something like:
```js
const computedRole = roleAttribute
    ?.split(' ')
    .find(splitRole => ariaRoles.find(role => splitRole === role))
return computedRole || null
```
It's up to you to use it here or in your future works.

2020-10-23 19:28 UTC, zthaver commented
> LGTM now, thanks for quick response. Just a suggestion, your logic can be shortened into something like:
> 
> ```js
> const computedRole = roleAttribute
>     ?.split(' ')
>     .find(splitRole => ariaRoles.find(role => splitRole === role))
> return computedRole || null
> ```
> 
> It's up to you to use it here or in your future works.

Wow, that looks way cleaner, I will try and put it in and see if it works. Thanks for the tip!

2020-10-23 19:44 UTC, pynnl commented
> 
> 
> > LGTM now, thanks for quick response. Just a suggestion, your logic can be shortened into something like:
> > ```js
> > const computedRole = roleAttribute
> >     ?.split(' ')
> >     .find(splitRole => ariaRoles.find(role => splitRole === role))
> > return computedRole || null
> > ```
> > 
> > 
> > It's up to you to use it here or in your future works.
> 
> Wow, that looks way cleaner, I will try and put it in and see if it works. Thanks for the tip!

You can also use `includes` instead of `find` in the nested callback. More info [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)

2020-10-23 21:13 UTC, pynnl approved these changes

2020-10-27 18:18 UTC, MeisterRed approved these changes

2020-11-04 07:09 UTC, poftadeh approved these changes

2020-11-04 14:32 UTC, merged