refactor: extended express router to change request ype
Seneca-CDOT/plumadriver pull request #218
Opened 2020-11-12 19:09 UTC by zthaver

Extended the Router class to change the request types to avoid unnecessary null checks

Closes #209

2020-11-13 20:47 UTC, pynnl commented on 5.0.0-alpha.8
> ++ express@4.17.1
Why does this file exist?

2020-11-13 20:47 UTC, pynnl commented on src/Types/types.d.ts
> +
Redundant blank line.

2020-11-13 20:47 UTC, pynnl commented on src/utils/utils.ts
>      const release = await req.session?.mutex.acquire();
Now `req.session` is not optional anymore, we can remove the check. There might be other places like this which don't show up on github for reviewing, please fix them all.

2020-11-13 20:47 UTC, pynnl commented on src/Types/types.d.ts
> +  interface RequestSession extends ExpressRequest {
The name seems to be a bit wrong I guess. Shouldn't it be `SessionRequest`?

2020-11-13 20:47 UTC, pynnl commented on src/routes/cookies.ts
> +const routerSession = (cookies as unknown) as Pluma.CustomRouter;
Shouldn't just casting `cookies` directly to the custom type be better?

2020-11-13 20:47 UTC, pynnl commented on src/routes/elements.ts
>    if (req.sessionRequest) {
No more check.

2020-11-13 20:47 UTC, pynnl commented on src/routes/elements.ts
> +const elementSession = (element as unknown) as Pluma.CustomRouter;
Same here, could have just casting `element` directly.

2020-11-13 20:47 UTC, pynnl commented on src/routes/index.ts
> +const routerSession = (router as unknown) as Pluma.CustomRouter;
The name here is also a bit wrong. It's supposed to be a router bounding to session routes, so it should be `sessionRouter` or something alike.

2020-11-13 20:47 UTC, pynnl commented on src/Types/types.d.ts
> +  interface CustomRouter
Just a suggestion, use more specific name, like `SessionRouter` (cause this is the router for session routes). Also, add a blank line before this.

2020-11-13 20:47 UTC, pynnl commented on src/Types/types.d.ts
> +      customCallback: (
Another suggestion, I see that this function type has been used a lot, maybe consider making it a separated type to avoid duplication?

2020-11-13 20:47 UTC, pynnl commented on src/Types/types.d.ts
>      interface Request {
Now that we explicitly define where to have a custom router type, maybe augmenting the global type not needed anymore?

2020-11-13 20:54 UTC, zthaver commented on src/Types/types.d.ts
> +  interface RequestSession extends ExpressRequest {
I guess the reason why i named it like that is because sessionRequest is one of the properties of this interface

2020-11-13 20:55 UTC, pynnl commented on src/Types/types.d.ts
> +  interface RequestSession extends ExpressRequest {
Ahh I see. Then we can use another name, cause this is supposed to be a request, not a session.

2020-11-13 21:04 UTC, zthaver commented on 5.0.0-alpha.8
> ++ express@4.17.1
not sure, but i'll remove it

2020-11-13 21:07 UTC, pynnl commented on 5.0.0-alpha.8
> ++ express@4.17.1
This looks like a log from `npm i`, probably has been accidentally saved into a file.

2020-11-19 16:48 UTC, pynnl reviewed
Thanks for making the changes. Just a few more suggestions and I think it should be good.

2020-11-19 16:48 UTC, pynnl commented on src/routes/index.ts
>    const release = await req.session?.mutex.acquire();
`req.session` is not nullable here anymore

2020-11-19 16:48 UTC, pynnl commented on src/utils/utils.ts
>      const release = await req.session?.mutex.acquire();
No need to check for `req.session` existence. There might be unnecessary nullability checks like this which are not visible for reviewing, please make sure to remove them all , as it is the whole purpose of this PR.

2020-11-19 16:48 UTC, pynnl commented on src/Types/types.d.ts
> +  interface Callback {
nit: consider using a more specific name

2020-11-19 16:48 UTC, pynnl commented on src/Types/types.d.ts
> +  interface SessionRouter
nit: blank space between interface code blocks

2020-11-20 16:14 UTC, zthaver commented on src/utils/utils.ts
>      const release = await req.session?.mutex.acquire();
Tien, I don't understand how the highlighted line is a  nullability check. I thought I removed them

2020-11-20 16:17 UTC, pynnl commented on src/utils/utils.ts
>      const release = await req.session?.mutex.acquire();
Sorry for not being clear. It's the line below the highlighted one: `req.session?.`.

2020-11-20 16:18 UTC, zthaver commented on src/utils/utils.ts
>      const release = await req.session?.mutex.acquire();
Oh okay I understand, thanks

2020-11-24 18:40 UTC, pynnl requested changes
Thanks for making the change. I believe there are more null checks that can be skipped, for example (sorry Github won't let me comment directly at the line): https://github.com/Seneca-CDOT/plumadriver/blob/98e7208e9fdf74f2dff49cf0d9b2bab89476b8f0/src/routes/index.ts#L64

2020-11-24 18:40 UTC, pynnl commented on src/Types/types.d.ts
> +  interface CustomRequestCallback {
Sorry I forgot to mention in last review; you can define a function interface without having to wrap it inside a property. The syntax is:
```ts
interface myFunction {
(arg1: Type1, arg2: Type2): ReturnType
}
```

2020-11-24 19:17 UTC, zthaver commented
> Thanks for making the change. I believe there are more null checks that can be skipped, for example (sorry Github won't let me comment directly at the line):
> 
> https://github.com/Seneca-CDOT/plumadriver/blob/98e7208e9fdf74f2dff49cf0d9b2bab89476b8f0/src/routes/index.ts#L64

for this one, I had tried to remove the optional on release but it complains it is possibly undefined if I do

2020-11-24 19:22 UTC, pynnl commented
> > Thanks for making the change. I believe there are more null checks that can be skipped, for example (sorry Github won't let me comment directly at the line):
> > https://github.com/Seneca-CDOT/plumadriver/blob/98e7208e9fdf74f2dff49cf0d9b2bab89476b8f0/src/routes/index.ts#L64
> 
> for this one, I had tried to remove the optional on release but it complains it is possibly undefined if I do

It shouldn't be undefined. Could you try it again just for confirmation?

2020-11-24 19:27 UTC, zthaver commented
> > > Thanks for making the change. I believe there are more null checks that can be skipped, for example (sorry Github won't let me comment directly at the line):
> > > https://github.com/Seneca-CDOT/plumadriver/blob/98e7208e9fdf74f2dff49cf0d9b2bab89476b8f0/src/routes/index.ts#L64
> > 
> > 
> > for this one, I had tried to remove the optional on release but it complains it is possibly undefined if I do
> 
> It shouldn't be undefined. Could you try it again just for confirmation?

Nevermind, false alarm, it worked

2020-12-01 18:31 UTC, MeisterRed approved these changes

2020-12-01 22:24 UTC, pynnl reviewed
I think there is still unnecessary null checks, like here: https://github.com/Seneca-CDOT/plumadriver/blob/a1e19342617c2331a8a573782b468e826c1b4424/src/routes/timeouts.ts#L7

I suggest using the a feature to find out where you're missing. Vscode has one, or you can search directly on Github.

2020-12-02 15:45 UTC, zthaver commented
> I think there are still unnecessary null checks, like here:
> 
> https://github.com/Seneca-CDOT/plumadriver/blob/a1e19342617c2331a8a573782b468e826c1b4424/src/routes/timeouts.ts#L7
> 
> I suggest using a search feature to find out where you're missing. Vscode has one, or you can search directly on Github.

I just did a search and am aware of those. It tells me that the objects are possibly undefined if I remove the ?

2020-12-02 15:51 UTC, pynnl commented
> > I think there are still unnecessary null checks, like here:
> > https://github.com/Seneca-CDOT/plumadriver/blob/a1e19342617c2331a8a573782b468e826c1b4424/src/routes/timeouts.ts#L7
> > 
> > I suggest using a search feature to find out where you're missing. Vscode has one, or you can search directly on Github.
> 
> I just did a search and am aware of those. It tells me that the objects are possibly undefined if I remove the ?

It works on my clone. Could you check it again? I'm down if a call is needed.

2020-12-03 20:08 UTC, pynnl approved these changes

2020-12-03 20:58 UTC, MeisterRed approved these changes

2020-12-07 20:30 UTC, manekenpix approved these changes

2020-12-07 20:33 UTC, merged